#!/usr/bin/env bash

set -u -e -o pipefail

case "$*" in
  "")
    set -x
    sh/build
    deployctl run --libs="" --watch ./deno_deploy/deploy.js
    ;;

  "html")
    set -x
    da.ts file server start 3456 "./render.ts"
    ;;

  *)
    echo "!!! Unknown commands: $0 $*" >&2
    exit 2
    ;;
esac
